<?php

if(function_exists("register_field_group"))
{
	register_field_group(array (
		'id' => 'acf_product-info',
		'title' => 'Product Info',
		'fields' => array (
			array (
				'key' => 'field_53b55080286fc',
				'label' => 'Product title',
				'name' => 'title',
				'type' => 'text',
				'instructions' => 'Put the product title. (ex: product name)',
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'html',
				'maxlength' => '',
			),
			array (
				'key' => 'field_53b55e2be66d0',
				'label' => 'File Name',
				'name' => 'filename',
				'type' => 'text',
				'instructions' => 'Put the file name. (ex: product.exe)',
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'html',
				'maxlength' => '',
			),
			array (
				'key' => 'field_53b55f10e66d2',
				'label' => 'File Size',
				'name' => 'filesize',
				'type' => 'text',
				'instructions' => 'Product file size (ex: 20MB)',
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'html',
				'maxlength' => '',
			),
			array (
				'key' => 'field_53b560d493dca',
				'label' => 'Product Version',
				'name' => 'version',
				'type' => 'text',
				'instructions' => 'Put the product version.',
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'html',
				'maxlength' => '',
			),
			array (
				'key' => 'field_53b55e4de66d1',
				'label' => 'License',
				'name' => 'license',
				'type' => 'text',
				'instructions' => 'Product license (Premium, free, freeware, open source)',
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'html',
				'maxlength' => '',
			),
			array (
				'key' => 'field_53b5610ffb15c',
				'label' => 'Change Log',
				'name' => 'changelog',
				'type' => 'textarea',
				'instructions' => 'Write the product change log here.',
				'default_value' => '',
				'placeholder' => '',
				'maxlength' => '',
				'rows' => '',
				'formatting' => 'br',
			),
			array (
				'key' => 'field_53b55f35e66d3',
				'label' => 'Product Language',
				'name' => 'language',
				'type' => 'text',
				'instructions' => 'Languages supported by this product (ex: english,Spanish or multi-languages )',
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'html',
				'maxlength' => '',
			),
			array (
				'key' => 'field_53b55f8ae66d4',
				'label' => 'Requirements',
				'name' => 'requirements',
				'type' => 'text',
				'instructions' => 'Write requirements to install this product (ex: windows 7,windows 8,)',
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'html',
				'maxlength' => '',
			),
			array (
				'key' => 'field_53b55fe9e66d5',
				'label' => 'Author Name',
				'name' => 'author',
				'type' => 'text',
				'instructions' => 'Put the product author name.',
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'html',
				'maxlength' => '',
			),
			array (
				'key' => 'field_53b56002e66d6',
				'label' => 'Author URL',
				'name' => 'authorurl',
				'type' => 'text',
				'instructions' => 'Put author site url if exist.',
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'html',
				'maxlength' => '',
			),
			array (
				'key' => 'field_53b5617efb15d',
				'label' => 'Download Link',
				'name' => 'downloadlink',
				'type' => 'text',
				'instructions' => 'Put the file download link here',
				'save_format' => 'url',
				'library' => 'all',
			),
			array (
				'key' => 'field_5494403b03e13',
				'label' => 'Download Target Same/New Window',
				'name' => 'download_target',
				'type' => 'radio',
				'instructions' => 'Put button target value in the text field below.Same Window: _self & New Window:	_blank',
				'choices' => array (
				),
				'other_choice' => 1,
				'save_other_choice' => 1,
				'default_value' => '_self or _blank',
				'layout' => 'horizontal',
			),			


		),
		'location' => array (
			array (
				array (
					'param' => 'post_type',
					'operator' => '==',
					'value' => 'post',
					'order_no' => 0,
					'group_no' => 0,
				),
			),
		),
		'options' => array (
			'position' => 'normal',
			'layout' => 'no_box',
			'hide_on_screen' => array (
			),
		),
		'menu_order' => 0,
	));
}


?>